### ISSUE TITLE
Translate more than one book at once. Add options for translating Old or New Testaments and Deutero Canon.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#110]
I was sure that it was possible to tell the translate code to translate all the books of the NT or OT.  I couldn't figure out how to do that.
I tried various ways to specify the --book parameter such as:
--book OT
--book *OT
--book OT*
--book *OT*
In all cases it gave an error saying it couldn't find the file name:  00<book><project>.SFM
Where book was the exact parameter supplied in the command line: 00*OT*<project>.SFM

If it is possible to specify these could we add to the command line help text to describe them.

**Comment by ddaspit** [comment]
It doesn't look like the script currently supports translating a whole testament. We would need to add support for that.

**Comment by davidbaines** [comment]
Yes I think that's right. I had a look through the code and I think I'm remembering using the OT and NT options for extraction. 
Could we add NT and OT and DC, and ALL to refer to all three?

It would also be very helpful to be able to specify more than one book (or testament) at a time.

**Comment by johnml1135** [comment]
I think this is ready to use.  You can use on the #78 branch.
