### ISSUE TITLE
Preserve input versification structure in corpora extractions

### ISSUE THREAD

**Issue by DCNemesis** [sillsdev/silnlp#117]
I'm using the extract_corpora script and bulk_extract_corpora to align verses for direct comparisons for AQuA. However, once I have that information, I also need to be able to put it back into the versification of the draft from which the extraction came. Currently, this information is lost to the user. It would be great to have an output format that gave alignments to the original versification, but with the extra information. Maybe (for example) a json file where the first layer is a list of the same length as the number of lines as the standard output, and list item is a dictionary with the text, original versification and the input versification.

**Comment by ddaspit** [comment]
@DCNemesis I just want to make sure that I understand the requirement. You still want to align the verses to the Original versification, but you would also like to know the verse ref for a verse in the input versification as well. Is that correct? If so, you suggest a JSON file that contains the verse text, Original verse ref, and input verse ref. We could also output a separate text file that has the input verse refs. If you are only interested in extracting the verse text in the input versification and are not interested in aligning the text to the Original versification, then I would recommend that you use the Machine library directly. You can easily extract verse text using corpora classes in Machine. I can give you more information if you are interested.

**Comment by DCNemesis** [comment]
@ddaspit You've got it, basically. I'm less concerned about the form of the output. As you say, even a line-by line output of the input versification that parallels the text output would satisfy this (for me). To be more specific, we're putting all of our reference translations into bible-graph in original versification. So, we need the original versification for the comparisons, but we need the input versification so that we can output our comparison in a way that fits the draft translation work (which will be the expected versification for our output by our users).

**Comment by ddaspit** [comment]
Okay, I got it. This should be doable.

**Comment by ddaspit** [comment]
@DCNemesis I have added the ability to output the project verse refs to a separate text file. When you run the `extract_corpora` or `bulk_extract_corpora` scripts, add the `--project-vrefs` parameter in order to output the verse refs. The text file will be saved to a file with the name `<iso>-<project_name>.vref.txt`.
