### ISSUE TITLE
'use_test_set_from' parameter is not supported with ClearML experiments

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#131]
The 'data:use_test_set_from' parameter allows experiment A to use the test.vref.txt file from experiment B as its test set listing.    This requires preprocessing for experiment A to have access to the experiment B folder in order to reuse the test.vref.txt file.  If preprocessing is being done on using ClearML, however, the experiment B folder is not available; only the content of the experiment A folder is copied from the AWS S3 bucket to the temp folder on the AQUA server's local drive.

**Comment by ddaspit** [comment]
@isaac091 I think this might already be fixed. Can you ensure that it is working properly?

**Comment by isaac091** [comment]
Yes, it seems to be working.
