### ISSUE TITLE
Check for existence of required files at beginning of preprocessing

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/silnlp#14]
Currently, if there is a data file that does not exist, the `preprocess` script will fail when it attempts to read the file for the first time. This can occur deep into preprocessing, wasting the user's time. Also, the error messages can be confusing. It would be better to check for the existence of all required data files at the beginning of preprocessing and provide helpful error messages if any do not exist.

**Comment by johnml1135** [comment]
Check with @davidbaines for more details.

**Comment by johnml1135** [comment]
MT/scripture, MT/corpora, MT/terms.  When reading from those directories, log an error and quit.
Do this before you start the preprocessing.  Add the check at the beginning.

**Comment by johnml1135** [comment]
Implemented with @ddaspit's advice: "I would suggest that you perform the check at the beginning of the Config.preprocess() method in config.py. In that method, you could iterate through self.src_file_paths and self.trg_file_paths and check if each file exists. If a file doesn't exist, you would raise an exception."
