### ISSUE TITLE
Omit <range> markers from the extracts where there is no verse text.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#142]
Some of our extracted files contain sections where there is an empty verse followed by a number of range markers.
The extracts would be cleaner if those range markers were omitted.

Avoid extracts that contain data like this:
```


<range>
<range>
```

**Comment by davidbaines** [comment]
It seems as though this isn't a problem, or it is already fixed.

**Comment by davidbaines** [comment]
This is a small issue. It's easy to fix in post processing, but would be better fixed in paratext.py

I checked over the recent Paratext extracts and found these stats:

There are 1760 files, of which 76 have 'empty' ranges.
There are a total of 24742105 verses, with content this includes <range> markers.
There are a total of 294130 ranges. 1.19% of verses are ranges.
There are a total of 1312 empty ranges. 0.005% of verses are empty_ranges
0.446% of ranges are empty_ranges.

**Comment by davidbaines** [comment]
[ranges.py](https://github.com/BibleNLP/ebible/blob/1844ae767b99dbaa7c4263f4ade14b12e6271a4d/code/python/ranges.py) in the ebible repo does this as a post processing step.

**Comment by ddaspit** [comment]
This should be fixed now. @davidbaines, can you test this to ensure that I fixed the problem and didn't mess up anything else? Thanks.
