### ISSUE TITLE
Documentation on pipeline usage

### ISSUE THREAD

**Issue by sete-nay** [sillsdev/silnlp#146]
Hi, where can I find documentation on usage of the pipelines in connection to specific tasks? E.g., I'm interesting in text preparation (cleaning, filtering, etc.) and alignment for parallel corpus creation. I'm a beginner in NLP and looking for documentation that could help me get started with your toolkit. Thank you.

**Comment by ddaspit** [comment]
Unfortunately, we don't have much documentation. SIL NLP is primarily built to support Bible translation research for the NLP team in SIL International. I would be happy to help in any way that I can. Can you give more information on what you would like to use the toolkit to achieve?

**Comment by sete-nay** [comment]
Is the toolkit only suitable for Bible texts? E.g., I have raw texts (books) that I want to preprocess - get clean text with sentences arranges in separate row, so I can align it with translations. Would that be possible?

**Comment by ddaspit** [comment]
I think you might find that the [Machine](https://github.com/sillsdev/machine.py) library might be able to help you achieve your task. It has various classes for processing Scripture and text corpora. Check out the [corpus tutorial](https://nbviewer.org/github/sillsdev/machine.py/blob/main/samples/corpora.ipynb).
