### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by sete-nay** [sillsdev/silnlp#147]
Hi, Im trying to extract  corpora from a file and get this error:

Traceback (most recent call last):
  File "silnlp/silnlp/common/extract_corpora.py", line 7, in <module>
    from ..common.corpus import count_lines
ImportError: attempted relative import with no known parent package

Could you help with that?

**Comment by ddaspit** [comment]
Can you give me more information on what command you are trying to run and what you are trying to achieve?

**Comment by sete-nay** [comment]
I have a Bible translation in low-resource language (Kabardian), several parts of OT and the full NT . I'm trying to extract this text with verse alignment, each verse in a separate row.  I cloned the repo and I tried to run  !python silnlp/silnlp/common/extract_corpora.py Bible/Bible_kbd.txt  in Google Colab, after that I get the error in description.

**Comment by ddaspit** [comment]
SIL NLP uses a library to extract verse text from a Bible translation in USFM/USX format and align it to a versification. It might be easier for you to use the library directly. It is called [Machine](https://pypi.org/project/sil-machine/). Here is a [Colab notebook](https://colab.research.google.com/drive/1q50OKJD7gDuKYAxN01l3mBaS2sS3B6yL?usp=sharing) that demonstrates how to use Machine to extract verse text from USFM data and align it to "Original" versification.

**Comment by sete-nay** [comment]
I checked the Machine library, the problem is I don't have data in USFM or any other structured format. What I have is a Bible in a book format (with titles, chapters, paragraphs, etc.) - noisy text. The verses in this text are already numbered according to Original versification. Is there a function I could use that can help me extract that text verse by verse and align it to [vref.txt](https://github.com/BibleNLP/ebible/blob/main/metadata/vref.txt)? What I need in the end is a text file with each verse on a separate row according to vref.txt.

**Comment by davidbaines** [comment]
Machine only reads structured data, usually we are reading USFM. Most other structured formats can be converted to USFM using [Haiola](https://haiola.org/).  What format is your data in at the moment? Could you provide a sample of it?

**Comment by sete-nay** [comment]
> I've only used Machine to read USFM. Most other structured formats can be converted to USFM using [Haiola](https://haiola.org/). What book format is your data in at the moment? Is it a PDF or Word document or something else? If it's in Word and the formatting for the Verse numbers and Chapters are consistent it might be possible to use a python script using [textract](https://textract.readthedocs.io/en/stable/) to convert it into SFM format. Do you have a sample of the data that you could share?

Thank you so much, I will check out these tools! My data is in [epub](https://ibt.org.ru/ftpmirror/pub/ebook/KBD/KBDOP/%D0%A5%D1%8A%D1%8B%D0%B1%D0%B0%D1%80%D1%8B%D1%84%D3%80%D1%8B%D1%80-%E2%80%A2-%D0%A9%D3%80%D1%8D%D0%B4%D0%B7%D0%B0%D0%BF%D3%80%D1%8D%D1%80-%E2%80%A2-%D0%A3%D1%8D%D1%80%D1%8D%D0%B4-%D0%9B%D1%8A%D0%B0%D0%BF%D3%80%D1%8D%D1%85%D1%8D%D1%80__Tran.epub?_ga=2.141517810.1724416982.1669648543-306919933.1665490063) and [azw3](https://ibt.org.ru/ftpmirror/pub/ebook/KBD/KBDOP/%D0%A5%D1%8A%D1%8B%D0%B1%D0%B0%D1%80%D1%8B%D1%84%D3%80%D1%8B%D1%80-%E2%80%A2-%D0%A9%D3%80%D1%8D%D0%B4%D0%B7%D0%B0%D0%BF%D3%80%D1%8D%D1%80-%E2%80%A2-%D0%A3%D1%8D%D1%80%D1%8D%D0%B4-%D0%9B%D1%8A%D0%B0%D0%BF%D3%80%D1%8D%D1%85%D1%8D%D1%80__Tran.azw3?_ga=2.173458403.1724416982.1669648543-306919933.1665490063) formats, downloaded from [Institute for Bible translation](https://ibtrussia.org/en/media?id=KBD&_ga=2.139873523.1724416982.1669648543-306919933.1665490063). I tried to use Machine on epub files but couldn't extract any data so far. Do you think it might work with epub or azw3?

**Comment by davidbaines** [comment]
I had a look at the epub files. You can unzip them and see that they are a collection of xhtml files. It should be possible to convert those into sfm format.

IBT almost certainly have these files in USFM format.  Perhaps you could ask them whether they would make those available to you?  If they would like to make those scriptures more available (as there are many Karbadian speakers around the world) then [eBible](ebible.org) would be very happy to host them in multiple formats.

**Comment by sete-nay** [comment]
Yes, I tried to use Machine on those xhtml files, but it didn't work. Probably need to convert them first, before using Machine.
I contacted the IBT for the data, if I manage to extract the data and they approve its publishing - will get in touch to add it to eBible collection.

**Comment by ddaspit** [comment]
Unfortunately, Machine does not support any unstructured display formats, such as HTML, ePub, azw3, etc. You would need to find some way to convert it to a structured format. Most likely that would require custom parsing.
