### ISSUE TITLE
Add a single script to execute entire NMT pipeline

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/silnlp#15]
There are multiple steps in the NMT pipeline. Currently, each step must be executed individually. It would be helpful to provide a single script that can execute the entire pipeline. It would also be helpful if the script could run the pipeline on multiple experiments.

**Comment by johnml1135** [comment]
Meeting minutes with @ddaspit on how to proceed:
*** Preprocess**
 * Run --stats on things a little larger than the size of a Bible.  Add the switch, put in the yaml file
  * Hey, we can even plot the bible alignment stats by book in clearML!
 * Ignore corpora filtering in preprocess right now.  It can theoretically be run in ClearML, but can also be done on our computers.  Don't exclude it or make any special flags for it.
*** train**
 * Mixed precision - yet.  The GPU's can support it
 * memory growth - no, it is faster to just allocate all the GPU memory up front.  It's docker and we have complete control of the GPUs
 * num-devices - replace with "just use all that you can see" - there is likely a way to do this in tensorflow that is easy.
 * eager execution - no, this is for debugging
*** test**
 * Start with basic statistics on last and best
 * Add more as it get to working well
 * Hopefully this stabalizes quickly.  If it does not, then we may need to add a separate "test" experiment to get extra data on an existing model
*** S3 Bucket**
 * Write all files to a temp directory and then push them to a S3 bucket when complete (have a massive try/catch. Whatever is in the folder, move to the S3 bucket when complete.  Record the S3 bucket name prominently in ClearML to be referenced later)
