### ISSUE TITLE
Eflomal local setup documentation

### ISSUE THREAD

**Issue by isaac091** [sillsdev/silnlp#205]
Document setup process for when support is added to docker containers.

**Comment by isaac091** [comment]
### Eflomal Setup
1. Open silnlp folder in a terminal
2. Install eflomal and cython:
    ```
    poetry install -E eflomal
    ```
    * Alternatively, run `pip install .` from inside the eflomal folder (and while in the virtual environment) once the repo is cloned.
3. Clone eflomal repo:
    ```
    git clone https://github.com/robertostling/eflomal.git
    ```
4. Compile eflomal binary:
    ```
    cd eflomal
    make -C src
    sudo make -C src install
    ```
5. Save the location of the binary as an environment variable named EFLOMAL_PATH:
    ```
    export EFLOMAL_PATH="/usr/local/bin"
    ```

**Comment by ddaspit** [comment]
Is there any reason why we need to keep this issue open?
