### ISSUE TITLE
When there's nothing to translate, output nothing.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#219]
I'm not sure what happened here. 
I created a back translation model and used it to create a draft back translation.
Many verses in the source are empty. The book, chapter and verse markers all appear in the project but there is no content, just a space after the verse number as required.
For most verses like that there was nothing output as expected. For 1Kings every empty verse was back translated as:

This is not a sign for sin like this,

Would it be worthwhile to preprocess the input for inferencing so that we never ask for translations of empty lines?
Perhaps the code already works that way, and this is another anomaly.

**Comment by ddaspit** [comment]
This sounds like a bug. It shouldn't try to translate an empty verse.

**Comment by isaac091** [comment]
Fixed in #519
