### ISSUE TITLE
extract_corpora can create extract files with the wrong number of lines, and which are not aligned with the reference translation (Ref)

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#22]
When these projects are extracted, they have the wrong number of lines:

- nheBI (31132)
- nhwBI (31132)
- nchBI (31132)
- ngu (31105)
- azzNT (31105)
- nclNT (31105)
- nhyNT (31105)
- ncjNT (31105)
- nhgNT (31105)

**Comment by johnml1135** [comment]
This is related to #9.  #9 give the error message, this one is what is actually going wrong.
