### ISSUE TITLE
Facilitate drafting from different source texts, don't overwrite existing drafts.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#225]
Once a model has been trained. We sometimes want to translate two or more sources.  The result of the last inferencing currently overwrites the first inferencing of the same book.

E.g Translate RUT from ULB and it creates this file:  MT/experiments/series/experiment/infer/steps/08RUT.SFM 
Then translate RUT from the NRSV and that file is overwritten.

Suggestion: Include the source project and date in the file name:
MT/experiments/series/experiment/infer/steps/08RUT_engULB_2023_11_05.SFM 
MT/experiments/series/experiment/infer/steps/08RUT_NRSV_2023_11_05.SFM

**Comment by davidbaines** [comment]
An additional enhancement would be to consider adding a remark as the second line of each translated SFM file. 
I'm doing this manually to indicate which model created the draft.

The first line of the SFM file must be the \id which indicates the source that was translated.
An example would be:
\rem Drafted by the model FT-Edolo/NLLB1.3_en_etr_1/19000

Note that "\" must be avoided within the line as they are treated as inline markers. Use forward slashes instead.

**Comment by davidbaines** [comment]
I think you're right, since we plan to add the date into the remark there's no need to have it in the filename.  Also, since we are planning to add the source into the remark we might be able to simplify this by using a source folder instead of including the source in the file name. In that case we would output to a different folder for each source.

This looks a lot neater to me:
MT/experiments/series/experiment/infer/steps/ULB/08RUT_eng.SFM

**Comment by mshannon-sil** [comment]
Sounds good, I'll submit a PR for this.
