### ISSUE TITLE
extract_corpora cannot process terms files with UTF-16 encoding

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#23]
In the Paratext project, the _TermRenderings.xml_ can use UTF-16 encoding; e.g.:

    `<?xml version="1.0" encoding="utf-16"?>`

The _extract_corpora_ script will fail when extracting the terms from these projects.

**Comment by johnml1135** [comment]
This should be a simple fix.  I'll try this.

**Comment by johnml1135** [comment]
This issue is related to this post: https://stackoverflow.com/questions/24045892/why-does-elementtree-reject-utf-16-xml-declarations-with-encoding-incorrect

**Comment by johnml1135** [comment]
Solution: replace xml ElementTree parser with lxml etree: https://lxml.de/1.3/compatibility.html.  This looks like the best solution as xml ElementTree is pretty old and has limited functionality.

**Comment by johnml1135** [comment]
nheBI project has utf-16 encoding.
