### ISSUE TITLE
Update poetry to latest version for dev and for dockerfile

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#238]
Do it.  There was an issue that prevented updating back at poetry ~1.2.  That issue is likely resolved.  Let's see if it works.

**Comment by mshannon-sil** [comment]
I was able to upgrade to poetry version 1.7.1. The only complication is that after an experiment with poetry 1.7.1 is run on the server, experiments run by others with poetry 1.2.2 start to hang when installing poetry requirements. An issue that was very similar to this where multiple versions resulted in poetry installations hanging was resolved in poetry 1.3 (https://github.com/python-poetry/poetry/pull/7137), so I'm hopeful that after everyone pulls the new version of SILNLP with poetry 1.7.1 we shouldn't run into this issue again the next time we go to upgrade poetry.
