### ISSUE TITLE
uniform logging

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#25]
LOGGER = logging.getlogger()

Save to file, print to screen, enable "DEBUG" switch in modules.
Replace "print" statements

**Comment by davidbaines** [comment]
If this will save the output from tensorflow that we get when the we run the tools in the pipeline that could be useful. I was trying to use the tee command to do that months ago but I wasn't very consistent with it and gave up when I started running experiments on linux. Thumbs up for this issue.
