### ISSUE TITLE
Suppress "..." verses in extract files

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#267]
Paratext skeleton USFM files for to-be-translated books can have placeholder text of "..." associated with some of the USFM markers.  This placeholder text is often included in the verse extract file as the verse text, which can lead to poorer machine translation results if its used for model training.

If this placeholder text can be prevented from showing up in the verse extract files, machine translation results may improve.

Example 1:
```
\c 37
\p
\v 1
\v 2
\p ...
\v 3
\v 4
\p
\v 5
\v 6
```

Example 2:
```
\v 17
\v 18
\v 19
\v 20
\q1
\q1
\m ...
\v 21
\v 22
```

**Comment by isaac091** [comment]
Same as #153
