### ISSUE TITLE
"Poetry shell" failing to create a virtual environment on fresh install of SILNLP

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#305]
After cloning silnlp and changing into the directory I tried running poetry shell and it fails with an error that Additional properties are not allowed.
```
C:\Users\David\Documents\GitHub\silnlp>poetry shell

The Poetry configuration is invalid:
  - [source.0] Additional properties are not allowed ('priority' was unexpected)
```

**Comment by ddaspit** [comment]
It sounds like you might need to upgrade Poetry to the latest version.

**Comment by davidbaines** [comment]
Thanks Damien, that was exactly the problem.
