### ISSUE TITLE
French-to-vernacular drafting - KBT's are not included in training data

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#309]
When preprocessing the configuration for a French-to-vernacular experiment, the glosses were not added to the training dataset.  The project uses the Major KBT list; ~1,000 KBT's were extracted during the project extract step and should be available for training.

It appears that the corpus.py: get_terms() method defaults to loading Paratext's English glosses (en-Major-glosses.txt) when it constructs the terms list, and then these terms not not used later since they are not French/vernacular term pairings.

See: FT-Mali\NLLB1.3B.fr-PDV.dux-DUX

**Comment by mshannon-sil** [comment]
This was completed by PR #332. I also tested a copy of the experiment and confirmed the terms are appearing in the training data now.
