### ISSUE TITLE
When translating on a USFM file with a table spanning multiple verses, the output USFM drops some verse markers and table formatting markers 

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#329]
When the _translate_ script is run on a USFM file with a table that spans multiple verses, the output USFM file can omit mid-table verse markup as well as some of the table formatting markers.

As an example, the first attached file shows the USFM source for the NIV11R's version of NEH 7:7-39.  A single table spans verses 7-38, and a second table begins in verse 39.  The second attached file shows the translated USFM generated by the _translate_ script, in which the verse markers for verses 8-37 are missing ("\v 7" through "\v 38"); in addition, the table format markers "\tc1" and "\tcr2" are missing from the output.  The output USFM doesn't include verse markers until verse 39, in which the next table starts.
[NIV11R (NEH 7.7-39).txt](https://github.com/sillsdev/silnlp/files/14378131/NIV11R.NEH.7.7-39.txt)
[Mashi Draft (NEH 7.7-39).txt](https://github.com/sillsdev/silnlp/files/14378132/Mashi.Draft.NEH.7.7-39.txt)

**Comment by ddaspit** [comment]
As a part of this issue, we should move to Machine for USFM parsing and generation. I believe that Machine supports table markers better.

**Comment by mmartin9684-sil** [comment]
Would there be any other types of USFM markers where it would be helpful for us to double-check the way the markers are being handled in the drafts? Maybe we could do a little survey of what we're seeing in the drafts for markers where you suspect there could be problems.

**Comment by ddaspit** [comment]
The least tested USFM markers would probably be [tables](https://ubsicap.github.io/usfm/tables/index.html), [milestones](https://ubsicap.github.io/usfm/milestones/index.html), [spacing and break markers](https://ubsicap.github.io/usfm/characters/index.html#spacing-and-breaks), and study Bible markers, such as [sidebars](https://ubsicap.github.io/usfm/notes_study/sidebars.html). Machine should have better support for most of these markers.

**Comment by isaac091** [comment]
Using the machine.py parser, tables are handled much better, at least for these examples. See the attached file. All of the markers are preserved, though like in other situations where there are multiple markers in a verse, all of the pieces of the translated verse are inserted into the first text element which is directly after the verse marker. The "~~" bits are still missing, but I suspect that's related to the normalization done by the NLLB tokenizer, akin to the issues in #297.

[16NEH7.txt](https://github.com/user-attachments/files/17037483/16NEH7.txt)
