### ISSUE TITLE
When translating a passage with embedded paragraph markers ("\pm"), verses are output in the reverse order

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#330]
When the _translate_ script is run over a passage in a USFM file with embedded paragraph markers ("\pm") between the verses, the translated output has the translated verses in reverse order.

For example, the first attached file shows the source USFM for NEH 10:26-39 from NIV11R resource.  In this source USFM file, embedded paragraph markers are found between many of verses:

> \v26 \v27 \pm \v28 \v 29 \pm \v 30 \pm \v31 \pm \v32 v33 \pm v 34 \pm \v 35 \pm \v36 \pm \v 37 \v38 \v 39 \pm \c 11

The second attached file shows the translated USFM for the same passage, with translated verses in the wrong order:

> \v 27 \v 37 \v 38 \v39 \v 36 \v 35 \ v 34 \v 32 \v 31 \v 30 \v 28 \v29 \c 11

After the chapter break, verses in the translated USFM are found in the correct order.

[NEH 10.26-39 (NIV11R).txt](https://github.com/sillsdev/silnlp/files/14378475/NEH.10.26-39.NIV11R.txt)
[NEH 10.26-39 (Mashi).txt](https://github.com/sillsdev/silnlp/files/14378481/NEH.10.26-39.Mashi.txt)

**Comment by isaac091** [comment]
Resolved with the new parser
