### ISSUE TITLE
Multiple Scores

### ISSUE THREAD

**Issue by jcuenod** [sillsdev/silnlp#360]
When scoring the outputs of silnlp, why would I get more than one sets of scores?

I ran with the switch `--scorers bleu spbleu chrf` but I got 3 BLEU scores, 2 CHRF3 scores, and 2 spBLEU scores. I used a `mixed_source` config with 3 sources in two languages, not sure if that has something to do with it. Before I start digging through the code, just wondering if someone can tell me.

**Comment by ddaspit** [comment]
This can happen if the experiment is configured to test multiple language pairs. If you send us the config, we can tell you exactly what is happening.

**Comment by jcuenod** [comment]
Thanks, Isaac explained:

> Hello! You will get one set of scores for each language pair in your experiment, and an additional BLEU score at the end for all of the test data. The first three columns of the scores file/final output, `book,src_iso,trg_iso` denote which pair belongs to each score (`book` should always be ALL unless you use the `--score-by-book` option).
