### ISSUE TITLE
Add ISO codes to pair alignment filenames, add stats about trainable and draftable verses

### ISSUE THREAD

**Issue by isaac091** [sillsdev/silnlp#368]
It would be useful to add the iso code. I think that the alignments are calculated from an extracted file, and that file contains the iso code as part of the filename. That is the filename, less the .txt extension, which appears in the config.yml file. The code seems to remove that information from the corpus-stats.csv file.

Each file contains a total number of "verses-with-text", and it would be good to include that in a 'source: total verses' column. 

It would be useful to know the maximum number of verses available for training: - i.e. how many verses-with-text in the source also have text in the target.

It would be useful to know how much data is available for drafting. i.e. how many verses-with-text in the source are empty in the target.

_Originally posted by @davidbaines in https://github.com/sillsdev/silnlp/issues/317#issuecomment-2065809374_

**Comment by ddaspit** [comment]
@isaac091 Has this been done yet?
