### ISSUE TITLE
Orphan end markers are sometimes reported without a matching opening marker even though the opening marker exists.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#379]
To reproduce this issue test with the NIV11R_original or NRT23_original projects.

Parsing JOL from the NRT23 gives this error:
```
2024-05-09 17:36:22,364 - silnlp.common.translate - INFO - The following error occured while parsing JOL in project S:\Paratext\projects\NRT23_original
2024-05-09 17:36:22,364 - silnlp.common.translate - INFO - S:\Paratext\projects\NRT23_original\JOLrusNRT23.SFM: line 45,47: orphan marker \fr: may only occur under \ef, \f, \fe
```
The text of that line is:
`\q2 доела пожирающая саранча.\f + \cat ex\cat*\fr 1:4 \ft В этом стихе на языке оригинала для обозначения саранчи использованы четыре слова. Эти слова могут быть либо просто синонимами, либо терминами, которые отражают четыре стадии развития саранчи. То же в \+xt 2:25\+xt*.\f*\f + \cat st\cat*\fr 1:4 \ft Точное значение этих четырех евр. слов, использованных в отношении саранчи неясно.\f*`

`\fr` occurs after the '\f' marker twice on the line. Both occurrences have the unknown '\cat ... \cat*' markers in between.

There are several errors like this reported and it would be ideal if the code could cope with them.
Setting the --stylesheet-field-update to ignore doesn't seem to prevent this error.

This example is from EZR in the NIV11R_original project where line 303 is:
```\v 14 He even removed from the temple\f + \fr 5:14 \ft Or \fqa palace\f* of Babylon the gold and silver articles of the house of God, which Nebuchadnezzar had taken from the temple in Jerusalem and brought to the temple\fm \f + \fr 5:14 \ft Or \fqa palace\f*\fm* in Babylon. Then King Cyrus gave them to a man named Sheshbazzar, whom he had appointed governor,```

The error is:
```INFO - S:\Paratext\projects\NIV11R_original\15EZRusNIV11.SFM: line 303,259: orphan end marker \fm*: no matching opening marker \fm```

The `\fm*` occurs after a `\fm` marker and there are several other opening and closing markers in between. The error occurs in many books of the NIV11R

These books fail to parse in the NIV11R: GEN LEV NUM DEU JDG 1KI 1CH 2CH EZR PSA ISA JER LAM DAN MAT MRK LUK JHN ACT ROM 1CO HEB REV
All books of the NRT23 fail to parse.

Adding 
```
\Marker cat
\Name unknown
\Endmarker cat*
```
To the custom.sty removes SyntaxWarnings but still all the books fail to parse, with errors about orphan markers.

**Comment by isaac091** [comment]
Resolved with the new parser

**Comment by jcuenod** [comment]
Hey @isaac091, I've just pulled the latest code to be sure but when translating from NIV11R I'm getting:

> SyntaxError: ~/silnlp_data/Paratext/projects/NIV11R/01GENusNIV11.SFM: line 77,96: orphan end marker \nd*: no matching opening marker \zms1

**Comment by jcuenod** [comment]
Thanks @davidbaines, my mistake. I had pulled but not noticed that there was a merge issue (local modifications). It appears to be working. Apologies @isaac091.
