### ISSUE TITLE
Translate script gives zero exit code on failure

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/silnlp#389]
The translate script seems to give a zero exit code even on failure sometimes. See [here](https://app.sil.hosted.allegro.ai/projects/a013a325785b4b34bfb5e69f072c0976/experiments/d27e45b255934df794ff0eb8e8e47a92/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=). This means that the clearml job will say 'completed' not 'failed' even though it's failed. This makes it difficult for the Onboarding App to distinguish successful and failed jobs.

**Comment by isaac091** [comment]
It's set up this way so if multiple books are being translated, failing on one book doesn't prevent the others from getting translated. Is there something else we could add that the onboarding app could easily read to see the status of translate requests  instead of making the Task fail?

**Comment by Enkidu93** [comment]
Would it be possible to still return a non-zero code if *any* of the translation jobs fail while still cuing the user into the fact that some books did not fail? It is possible to workaround but fairly messy since the assumption is that 'completed' means everything has gone on without a hitch.

**Comment by isaac091** [comment]
Tentative solution:
* Note when a translation fails and fail the job only after any other translations complete
* Prevent retranslations of the same book on the same checkpoint so that extra work is not done if the translate script is rerun with the same request
