### ISSUE TITLE
Parsing error causes a failure

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#4]
One other issue that's come up - usfm.parser routine is throwing an error parsing the book '28HOSLIM-Nep.SFM' in the resource folder 'LIMnbt-2021-01-22'.  Here's the stack trace:

> Traceback (most recent call last):
> File "C:\Users\mm9q\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
> "_main_", mod_spec)
> File "C:\Users\mm9q\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\infer_google.py", line 191, in <module>
> main()
> File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\infer_google.py", line 187, in main
> google_infer_book(src_project, book, output_path, src_iso, trg_iso, replace_angle_brackets)
> File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\nmt\infer_google.py", line 112, in google_infer_book
> doc = list(usfm.parser(book_file))
> File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\sfm\_init_.py", line 709, in default
> self.__pp_marker_list(meta["OccursUnder"]),
> File "C:\Users\mm9q\PycharmProjects\silnlp\silnlp\sfm\_init_.py", line 594, in _error
> raise SyntaxError(msg)
> SyntaxError: C:\Gutenberg\Paratext\Paratext.unzipped\LIMnbt-2021-01-22\28HOSLIM-Nep.SFM: line 39,1: orphan marker \v: may only occur under \d, \lf, \lh, \li, \li1, \li2, \li3, \li4, \lim, \lim1, \lim2, \lim3, \lim4, \m, \mi, \nb, \p, \pc, \ph, \phi, \pi, \pi1, \pi2, \pi3, \pm, \pmc, \pmo, \pmr, \po, \pr, \q, \q1, \q2, \q3, \q4, \qc, \qd, \qm, \qm1, \qm2, \qm3, \qr, \s3, \sp, \tc1, \tc2, \tc3, \tc4, \tcr1, \tcr2, \tcr3, \tcr4, \tr
> 

In looking at the source USFM file, it appears the logic is expecting a "\p" tag to be used between the chapter tag ("\c 2", line 38) and the verse tag ("\v 1", line 39).  If I edit the file to insert a "\p" tag between these two lines, the parsing is successful.Is this a true formatting error in the source file?  Or do we need a tweak to the parsing?

**Comment by johnml1135** [comment]
This should just preserve the formatting, if it is correct or incorrect.  It should just work.

**Comment by ddaspit** [comment]
This is incorrectly formatted USFM. Unfortunately, Paratext can produce invalid USFM, so we have to be able to deal with it.

**Comment by johnml1135** [comment]
So, the parser relies on https://github.com/sillsdev/silnlp/blob/3a152a4e398e02ba46077578a176a2634a22a920/silnlp/sfm/usfm_sb.sty#L717-L720

We really don't care about the style, just that it keeps the same format.  Should we be parsing the file properly at all?  Do we care more than "Here are a bunch of lines to translate"? - possibly in a few groups:
* Translation element: An uninterrupted line of text in the SFM file (no markers separating portions of it)
* Translation group: a group of translation elements such as a paragraph (or similar) to translate as one unit. This would extract out footnotes, squash poetry and potentially combine verses.  The extracted footnote would itself be it's own translation group.
 * This may need to be broken up if a paragraph is too long and we do not use the "performer" architecture.  Possibly, break up by paragraph, but if too many elements (say, 100), then break up by verse.

This would require likely a different type of parser, one where there would be three groups of symbols:
* translation element markers (anything with a leading "\")
* translation subgroup
 * Start: any footnote or cross reference "\[fx]"
 * End: The "end" sequence: "\\s+\*"
* translation group markers: paragraph, list, table, header, title, etc.

Parser flow:
* Break into translation elements
* Group translation elements by group and subgroup
* Find a service that will give word alignment: https://groups.google.com/g/google-translate-api/c/IO9-lEMrFkI?pli=1
  * https://cloud.yandex.com/en/docs/translate/
* Translate, use word alignment to re-create the original groupings

Benefits: works with non-compliant USFM formatted documents
Drawbacks: Loose which verse it came from in the program (the exported document will have the info readable by Paratext, etc.)

**Comment by johnml1135** [comment]
Alternatively, usfm_sb.py is "# Version=3.0.1" - we could make targeted updates to it, incrementing versions (3.0.2, etc.) to make the files parse properly.  The update needed (to my understanding) would be to append "c" to "\OccursUnder" for entry "\Marker v".

**Comment by johnml1135** [comment]
Or again, change sfm.__init__.py so that it will not raise an exception, but just go on, if a "don't raise exceptions on poorly formated things" is passed...

**Comment by johnml1135** [comment]
Added usfm_relaxed.sty that allows for this situation and can be adapted to future non-compliances as well.
