### ISSUE TITLE
Onboarding App: Auth timeout

### ISSUE THREAD

**Issue by Enkidu93** [sillsdev/silnlp#414]
After being logged in for a while, the auth seems to expire and causes silent errors.

**Comment by bhartmoore** [comment]
@pandanautinspace Any update on this issue? Thanks!

**Comment by Enkidu93** [comment]
The issues you described @bhartmoore should be resolved (they seem to actually be caching issues). There is an auth timeout issue as well. For now, the fix is to force the user to re-log-in. We can explore getting the token refresh to work properly. I think there's an incorrect setting somewhere in the google console.

**Comment by pandanautinspace** [comment]
Should be fixed in #487
