### ISSUE TITLE
Update to use Machine.py for USFM generation

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/silnlp#449]
There are a number of issues with USFM generation in the translate.py script:
- #329
- #444 
- #379 
- #367 
- #330 
- #329 
- #158 

Most of these issues would probably be fixed if we scrapped the USFM parser that we currently use in the translate.py script and use the `UsfmTextUpdater` from Machine.py.

**Comment by isaac091** [comment]
Another known issue: \b markers immediately following chapter markers cause empty sentences to be added to the parsing output.

**Comment by isaac091** [comment]
A few more issues to check after switching parsers:
- #467
- #456
- #338
- #219 (also #136)
