### ISSUE TITLE
Check that the required version of machine is installed prior to running preprocess.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#45]
I ran the preprocess script with a configuration for the Enhanced Alignment model. 
After two hours or so of processing it indicated that a newer version of Machine was required. 

It would be very helpful if that check could be made at the beginning.

[check_machine_preprocess.txt](https://github.com/sillsdev/silnlp/files/6638119/check_machine_preprocess.txt)

**Comment by ddaspit** [comment]
This has been fixed.
