### ISSUE TITLE
Unclosed \fe breaks usfm parser

### ISSUE THREAD

**Issue by jcuenod** [sillsdev/silnlp#467]
I'm getting `missing caller parameter after \\{token.name}` because of `missing caller parameter after \fe`. For example, a line of USFM:

> \v 31 At Ala nen yi mendek ndi mendek wakkagagerak nogo abok aret enegen kage nagagerik, <<Abu obeelom aret kagi,>> mbareegerak. Ti eereegerak nogo o kiip age, o weege, eeke ne ambi 6 aret agagerak.\fe

The text I'm working with actually has a bunch of these. I realize this is probably not valid usfm (I'm not sure), but is there a way to be less strict in parsing it and allowing the `\fe` to implicitly close?

(Perhaps related to #201)

**Comment by ddaspit** [comment]
In what context is this occurring? When you try to translate a book?

**Comment by jcuenod** [comment]
Yes

**Comment by ddaspit** [comment]
This issue is related to a host of issues with the USFM parser we are using in the translate script. We are in the process of replacing it with a parser that isn't as strict.

**Comment by ddaspit** [comment]
@isaac091 Can we close this issue?

**Comment by isaac091** [comment]
I didn't close it initially because I couldn't test the exact book, but I would imagine it did get fixed with the change.

**Comment by jcuenod** [comment]
I have not had this error since pulling the updates. I don't have enough context to reproduce this issue easily any more. But I'm going to close the issue, and, if it recurs, I'll reopen.
