### ISSUE TITLE
Check that the parent model exists when preprocessing child models.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#49]
Here's just a useful check to add for catching human error in running experiments. 
I ran a child model which specified a parent model. The parent model folder and config file existed and the parent config file had been preprocessed but not trained. So there were no subfolders in the parent folder.  It would be good to check that the parent model/checkpoint etc itself exists and that it has at least 3000 steps. (I haven't come across a parent model with 3000 or fewer steps).

That would prevent me from training a basic 1-1 model whose config file claims it to be a child model.

**Comment by johnml1135** [comment]
There are now more pre-checks to see if the files exist before we go forward.  I am closing this issue for now.
