### ISSUE TITLE
Add the translate section of the translate_config to the usual config.yml file.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#502]
Instead of requiring a separate translate_config.yml file the translate: section could be part of the config.yml file. 
The --translate option could be removed from the experiment.py code and experiments would translate iff the translate section is present. 

This would reduce file management and make it easier and quicker to configure projects that use this feature.

**Comment by Enkidu93** [comment]
+1 This would also make it much easier to automate within the onboarding dashboard and clowder proper.

**Comment by mshannon-sil** [comment]
During a recent team meeting, it was discussed that the `translate_config.yml` should remain separate from the `config.yml`. The `config.yml` is meant mainly for parameter configuration, whereas the `translate_config.yml` is less of a config and more just a place to store command line arguments for the `translate` module. I will close this issue for now, but feel free to reopen it if anyone feels it needs further discussion.
