### ISSUE TITLE
Compare two translations directly to show differences in model output

### ISSUE THREAD

**Issue by TaperChipmunk32** [sillsdev/silnlp#508]
Create a new script that will take in two translation outputs from a project, in either plain text or USFM and compute several evaluation metrics (BLEU, chrf, etc.) between them to show the difference in the two translations of the same project.

This can be used to show the effect of changes in the model (hyper-parameter changes, bug fixes, etc.) on the translation itself by comparing the full output translations directly, rather than just test scores.

**Comment by mshannon-sil** [comment]
Michael mentioned that we can safely remove the WER score from the results, since the Projects team no longer makes use of it to assess models these days. That would allow the script to be run independently of the SILNLP repo.
