### ISSUE TITLE
Upgrade transformers to the latest version

### ISSUE THREAD

**Issue by isaac091** [sillsdev/silnlp#521]
This is needed to be able to use SDPA for NLLB (#478), which should hopefully be released in the next minor version of transformers.

There may be others, but at least one breaking change that we will need to take care of is the refactoring of the `NllbTokenizer`, specifically in regards to the language code special tokens. This change came in 4.38, and I believe the main changes came in [this PR](https://github.com/huggingface/transformers/pull/27717).

**Comment by isaac091** [comment]
The changes should be coming in transformers 4.46

**Comment by TaperChipmunk32** [comment]
I believe the breaking change to the NLLB tokenizers is from version 4.42, in [this pr](https://github.com/huggingface/transformers/pull/29834). This is when they removed the deprecated attributes that we were using, such as id_to_lang_code. I was able to get machine.py to support up to version 4.41.2 without any breaking changes.

**Comment by isaac091** [comment]
4.46 is released and it looks like the changes are in there
