### ISSUE TITLE
Fix syntax that is currently only compatible with Python 3.9 or newer

### ISSUE THREAD

**Issue by mshannon-sil** [sillsdev/silnlp#538]
In `hugging_face_config.py`, pylance ran into an error for a couple "with" statements. Since having parenthesis for a with statement is apparently a Python 3.9+ feature, it's not allowing experiments to run that use Python 3.8.

**Comment by mshannon-sil** [comment]
The same issue is also in open_nmt_config.py.

**Comment by ddaspit** [comment]
We might be getting to the point where we need to start enforcing more code quality standards for this repo.
