### ISSUE TITLE
VSCode timing out when running debugger

### ISSUE THREAD

**Issue by mshannon-sil** [sillsdev/silnlp#551]
Multiple developers have encountered an issue where, some seconds after VSCode starts up the debugger, it quietly exits without beginning to step through the SILNLP repo code. It seems that the likely root cause of the issue is the default timeout in debugpy being too short. We've found that increasing the DEBUGPY_PROCESS_SPAWN_TIMEOUT in the ~/.profile of the container fixes the issue, so this environment variable should be added to the Dockerfiles.

**Comment by benjaminking** [comment]
I wonder if this will be improved by removing OpenNMT/Tensorflow?  Anecdotally, I've noticed that Tensorflow takes a long time to load when starting SILNLP.

**Comment by mshannon-sil** [comment]
It might help, but I'm not entirely sure. In the cases I've seen, the debugger exits before logging anything about Tensorflow (or in general) to the console, so it's hard to know for certain. We could wait to see the results of that before adding this fix to the containers.

**Comment by TaperChipmunk32** [comment]
I could add this to my [PR](https://github.com/sillsdev/silnlp/issues/521), since I am already updating the Dev container.

**Comment by mshannon-sil** [comment]
@TaperChipmunk32 that would be great.
