### ISSUE TITLE
extract_corpora not finding paratext projects because Environment.py chooses the AQuA folder in preference to the Gutenberg data.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#56]
I was trying to extract_corpora to get updated terms data and received a message to the effect that no projects could be found.
I discovered that in environment.py has the following code in lines 23-29 that defaults to the AQuA folder if it exists.

```    auqa_ml_path = Path("G:/Shared drives/AQUA")
    if auqa_ml_path.is_dir():
        return auqa_ml_path
    gutenberg_path = Path("G:/Shared drives/Gutenberg")
    if gutenberg_path.is_dir():
        return gutenberg_path
    return ROOT_DIR / "data"```

We could pass the full source folder as an argument instead, it's a general solution and avoids the possibility of extracting data from a guessed location.

**Comment by johnml1135** [comment]
use the environment variable to override.  It is checked first:
https://github.com/sillsdev/silnlp/blob/3eed9852fdd1e4e69551a7ed43d038ca08d3e920/silnlp/common/environment.py#L12-L14

**Comment by johnml1135** [comment]
We can notify the user which folder is being used.  It may be also smarter to force them to use the variable in the first place.  @ddaspit, what do you think?

**Comment by ddaspit** [comment]
I wouldn't worry about it too much. This is a pretty unique case, where David is trying to run silnlp locally and as a ClearML agent.

**Comment by davidbaines** [comment]
Yes, I'm trying to run silnlp locally, but not as a ClearML agent, at least not when this occurred.

**Comment by davidbaines** [comment]
It's also a problem for me on Windows, for example if I forget to set SIL_NLP_DATA_PATH and run silnlp.nmt.config then it appears to work, but I can't find the config in Gutenberg/MT/experiments because it has defaulted to AQuA/MT/experiments.

I'd prefer that the code told me that environment variable isn't optional than deciding for me where to put an experiment.

**Comment by johnml1135** [comment]
I believe the code changes resolve this issue enough by making it clear which environment was chosen.
