### ISSUE TITLE
Incorrect Versification Warning

### ISSUE THREAD

**Issue by bhartmoore** [sillsdev/silnlp#563]
In extracting project `BUR_2024_10_14`, the `extract_corpora` script gives a warning that the versification is incorrectly set to 0, and that detected versification is 4. However, the settings file includes the line `<Versification>4</Versification>` (and no other competing versification line).

**Comment by ddaspit** [comment]
@mshannon-sil Please take a look at this as soon as you have a chance.

**Comment by mshannon-sil** [comment]
@bhartmoore @ddaspit I took a look, and there's a custom.vrs file that is modifying the base versification. So even though the Settings.xml is set to 4, the `FileParatextProjectSettingsParser` sets the versification type to 0 (unknown) to reflect this, while setting the base versification type to 4. Given this, would you like to keep the current behavior, or is there an update you'd like to see for this to be more informative/helpful?

**Comment by mshannon-sil** [comment]
From a separate email conversation, we decided that for custom versifications, we can check the detected versification against the base versification type.
