### ISSUE TITLE
Update from Python 3.8 to Python 3.10 and from Ubuntu 20.04 to Ubuntu 22.04

### ISSUE THREAD

**Issue by TaperChipmunk32** [sillsdev/silnlp#577]
With the release of machine.py version 1.3 moving support to Python 3.9-3.12, we need to update silnlp to Python 3.9 at least. We have decided to target Python 3.10 and Ubuntu 22.04 to match Google Colab.

**Comment by ddaspit** [comment]
Google Colab is on Python 3.10 and Ubuntu 22.04. It probably makes sense for us to target the same environment as Colab.

**Comment by TaperChipmunk32** [comment]
> Google Colab is on Python 3.10 and Ubuntu 22.04. It probably makes sense for us to target the same environment as Colab.

Okay, I'll target those versions then, and I've updated the issue title.
