### ISSUE TITLE
Separate the reporting of verse counts from the alignment calculations.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#579]
The counting of verses is very fast compared to calculating alignments.  I would like to be able to look at the verse counts because they show me that I don't need to calculate the alignments for many pairs. When that is a three step process it is faster overall:
Step one: Display the verse counts. 
Step two: Remove the projects that are not useful. 
Step three: Calculate the alignments only for pairs with the required data.

**Comment by isaac091** [comment]
You can do the first step by using `collect_verse_counts.py` on its own. Granted, you do have to list out all of the files you want to count the verses of (e.g. --files en-NIV11;en-NIrV.txt). Something we could do to make this more convenient is if there is no files argument given, we can look to see if there is a config file in the given output folder and get the counts for every file listed in there.

**Comment by davidbaines** [comment]
Good to know about the collect_verse_counts.py 
However I am often am doing this for 20 or so files and it's not very practical to type them all out on the command line.
It would be ideal to pass the same folder as an argument to that and have it read the config.yml file for the list.
