### ISSUE TITLE
Integrate mono and split filtering into corpus filtering

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#6]
We need to figure out the best way to integrate it.  This will likely be by making a yml file for both the corpus (smt alignment thresholds) as well as the other filters - and then finding sane defaults by doing some weights and measures.

**Comment by johnml1135** [comment]
We need to also determine if removing characters that are not in the target or source language would help.

**Comment by johnml1135** [comment]
Connect with @mmartin9684-sil to confirm details.

**Comment by davidbaines** [comment]
I'm working on an experiment that will hopefully show whether filtering out unwanted characters will improve the model. In theory many of them are ignored anyway so it shouldn't make much difference. However there are thousands of different glyphs in our corpus data. The models use hundreds of them and automatically ignore the rarest ones. The question is whether limiting the data to a couple hundred characters or less will improve the models. Most scripts except the logographies used in China and Japan can be very well represented with two hundred characters or less.

**Comment by johnml1135** [comment]
Filtering has been found to not give as much benefit as we were desiring.  I am closing this issue.
