### ISSUE TITLE
Create series of experiments more easily.

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#66]
It would be ideal to be able to deal with series of experiments as a whole, rather than dealing with each one individually. 
A step along the way towards this would be to have a script that creates a series of experiment folders and config.yml files.

We could use an experiment series folder:
MT
    experiments
        series_1
            experiments.csv
            default_config.yml
            experiment_1
                config.yml
            experiment_2
                config.yml
            experiment_3
                config.yml

Here's one way I imagine this could be implemented:
1) Read a default_config.yml file for the series and specify for each variable the values that it can take. Perhaps right in that default_config.yml file)
2) Have the code calculate all the possible combinations of variables and create a spreadsheet for them. (series_experiments.csv or series_experiments.xlsx)

3) Have the user create names for all the experiments and add them into the spreadsheet, and optionally delete any unwanted experiments.
4) Have the code then create the experiment folders and config.yml files.

(Once we have a spreadsheet for the series it would be very helpful if the test scores and other useful data could be appended to the appropriate line. )

**Comment by johnml1135** [comment]
Creating a set of experiments can be done in ClearML.  That is the best way currently.
