### ISSUE TITLE
extract_corpora needs error checking for duplicated verses in the project

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#8]
One common error with the USFM markup in Paratext projects is duplication of verse ID's.  For instance:

\v 1-2 <verse 1 text>
\v 2 <verse 2 text>

When this happens, the duplicated verse ID causes an extra line in the extracted output file.  As a result, the extracted output file is not aligned properly with other extracted files.

**Comment by ddaspit** [comment]
This should be fixed now.
