### ISSUE TITLE
extract_corpora should generate a warning if the extracted file does not have the expected # of lines

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#9]
If _extract_corpora_ creates a verse extract file from a Paratext project, and the verse extract file does not have the same # of lines (verses) as the reference Paratext project, it should generate a warning / error message.

**Comment by johnml1135** [comment]
vref.text - in MT/scripture - the number of lines should match every scripture corpus file that is extracted.

**Comment by johnml1135** [comment]
Give an error - say the code did something wrong.

**Comment by johnml1135** [comment]
debug if match, error if no match
