### ISSUE TITLE
Preprocessing failed with an std::runtime_error (Possibly related to the normalization rule?)

### ISSUE THREAD

**Issue by davidbaines** [sillsdev/silnlp#94]
I ran the preprocessing script for experiment / nlg-en-2 
On my windows machine this preprocesses fine. I can transfer the results to the linux machine and train.
However on the linux machine I get the following error. 

Both repos are up to date and I ran `poetry install` after updating.
It's looking at local data so maybe there is a file present on the windows machine that is missing on the linux machine.

```
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
}
normalizer_spec {
  name: user_defined
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv: /home/david/silnlp/silnlp/nmt/nmt_nfkc.tsv
}
denormalizer_spec {}
terminate called after throwing an instance of 'std::runtime_error'
  what():  random_device could not be read
Aborted (core dumped)
(silnlp-gt_VMn9E-py3.8) david@pop-os:~/silnlp$ 
```

**Comment by ddaspit** [comment]
We found that this occurs on David's Linux box when using sentencepiece > 0.1.92. I'm not sure how widespread of an issue this is. We might need to revert sentencepiece back to 0.1.92.
